package org.mule.modules.neo4j.internal.exception;

import com.sun.org.apache.regexp.internal.RE;
import org.mule.runtime.extension.api.error.ErrorTypeDefinition;
import org.mule.runtime.extension.api.error.MuleErrors;

import java.awt.color.ICC_ColorSpace;
import java.util.Optional;

import static java.util.Optional.ofNullable;

public enum Neo4jErrors  implements ErrorTypeDefinition<Neo4jErrors> {
    CONNECTIVITY(MuleErrors.CONNECTIVITY),
    REQUEST_FAILED(CONNECTIVITY),
    INCORRECT_CREDENTIALS(CONNECTIVITY),
    UNKNOWN_HOST(CONNECTIVITY),
    INVALID_SESSION(CONNECTIVITY),
    CLIENT_CLUSTER_NOTALEADER(CONNECTIVITY),
    CLIENT_GENERAL_INVALID_ARGUMENTS(CONNECTIVITY),
    CLIENT_LEGACY_INDEX_NOT_FOUND(CONNECTIVITY),
    CLIENT_GENERAL_FORBIDDEN_READ_ONLY_DB(CONNECTIVITY),
    CLIENT_PROCEDURE_CALL_FAILED(CONNECTIVITY),
    CLIENT_PROCEDURE_NOT_FOUND(CONNECTIVITY),
    CLIENT_PROCEDURE_REGISTRATION_FAILED(CONNECTIVITY),
    CLIENT_PROCEDURE_TIMED_OUT(CONNECTIVITY),
    CLIENT_PROCEDURE_TYPE_ERROR(CONNECTIVITY),
    CLIENT_REUQUEST_INVALID(REQUEST_FAILED),
    CLIENT_REQUEST_TRANSACTION_REQUIRED(REQUEST_FAILED),
    CLIENT_SCHEMA_CONSTRAINT_ALREADY_EXISTS(INCORRECT_CREDENTIALS),
    CLIENT_SCHEMA_CONSTRAINT_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_SCHEMA_INDEX_ALREADY_EXISTS(INCORRECT_CREDENTIALS),
    CLIENT_SCHEMA_INDEX_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_SECURITY_EXPIRED(INCORRECT_CREDENTIALS),
    CLIENT_SECURITY_ENCRYPTION_REQUIRED(INCORRECT_CREDENTIALS),
    CLIENT_SECURITY_FORBIDDEN(INCORRECT_CREDENTIALS),
    CLIENT_SECURITY_UNAUTHORIZID(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_ARGUMENT_ERROR(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_ARITHMETIC_ERROR(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_CONSTRAINT_VERIFICATION_FAILED(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_ENTITY_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_EXTERNAL_RESOURCE_FAILED(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_LABEL_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_PARAMETER_MISSING(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_PROPERTY_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_SEMANTIC_ERROR(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_SINTAX_ERROR(INCORRECT_CREDENTIALS),
    CLIENT_STATEMENT_TYPE_ERROR(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_FORBIDDEN(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_MARKED_AS_FAILED(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_NOT_FOUND(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_TERMINATED(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_TIMED_OUT(INCORRECT_CREDENTIALS),
    CLIENT_TRANSACTION_VALIDATION_FAILED(INCORRECT_CREDENTIALS),
    ClIENT_NOTIFICATION_PROCEDURE_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_CARESIAN_PRODUCT_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_CREATE_UNIQUE_UNAVAILABLE_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_DYNAMIC_PROPERTY_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_EAGER_OPERATOR_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_EXHAUSTIVE_SHORTEST_PATH_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_FEATURE_DEPRECATION_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_JOIN_HINT_UNFULFILLABLE_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_JOIN_HINT_UNSUPPORTED_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_NO_APPLICABLE_INDEX_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_PLANNER_UNAVAILABLE_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_PLANNER_UNSUPPORTED_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_RUNTIME_UNSUPPORTED_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_UNKOWN_LABEL_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_UNKNOWN_PROPERTY_KEY_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_UNKOWN_RELATIONSHIP_TYPE_WARNING(REQUEST_FAILED),
    CLIENT_NOTIFICATION_STATEMENT_UNBOUNDED_VARIABLE_LENGTH_PATTERN_WARNING(REQUEST_FAILED),
    DATABASE_GENERAL_INDEX_CORRUPTION_DETECTED(REQUEST_FAILED),
    DATABASE_GENERAL_SCHEMA_CORRUPTION_DETECTED(REQUEST_FAILED),
    DATABASE_GENERAL_STORAGE_DAMAGE_DETECTED(REQUEST_FAILED),
    DATABASE_GENERAL_UNKOWN_ERROR(REQUEST_FAILED),
    DATABASE_SCHEMA_CONSTRAINT_CREATION_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_CONSTRAINT_DROP_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_INDEX_CREATION_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_INDEX_DROP_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_LABEL_ACCESS_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_LABEL_LIMIT_REACHED(REQUEST_FAILED),
    DATABASE_SCHEMA_PROPERTY_KEY_ACCESS_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_RELATIONSHIP_TYPE_ACCESS_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_SCHEMA_RULE_ACCESS_FAILED(REQUEST_FAILED),
    DATABASE_SCHEMA_SCHEMA_RULE_DUPLICATE_FOUND(REQUEST_FAILED),
    DATABASE_STATEMENT_EXECUTION_FAILED(REQUEST_FAILED),
    DATABASE_TRANSACTION_COMMIT_FAILED(REQUEST_FAILED),
    DATABASE_TRANSACTION_LOG_ERROR(REQUEST_FAILED),
    DATABASE_TRANSACTION_ROLLBACK_FAILED(REQUEST_FAILED),
    DATABASE_TRANSACTION_START_FAILED(REQUEST_FAILED),
    TRANSIENT_CLUSTER_NO_LEADER_AVAILABLE(REQUEST_FAILED),
    TRANSIENT_GENERAL_DATABASE_UNAVAILABLE(REQUEST_FAILED),
    TRANSIENT_GENERAL_OUT_OF_MEMORY_ERROR(REQUEST_FAILED),
    TRANSIENT_GENERAL_STACK_OVER_FLOW_ERROR(REQUEST_FAILED),
    TRANSIENT_NETWORK_COMUNICATION_ERROR(REQUEST_FAILED),
    TRANSIENT_SCHEMA_MODIFIED_CONCURRENTLY(REQUEST_FAILED),
    TRANSIENT_SECURITY_AUTH_PROVIDER_FAILED(REQUEST_FAILED),
    TRANSIENT_SECURITY_AUTH_PROVIDET_TIMEOUT(REQUEST_FAILED),
    TRANSIENT_SECURITY_MODIFIED_CONCURRENTLY(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_CONSTRAINTS_CHANGED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_DEADLOCK_DETECTED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_INSTANCE_STATE_CHANGED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_INTERRUPTED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_LOCK_ACQUISITION_TIMEOUT(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_LOCK_CLIENT_STOPPED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_LOCK_SESSIO_EXPIRED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_OUTDATED(REQUEST_FAILED),
    TRANSIENT_TRANSACTION_TERMINATED(REQUEST_FAILED),
    AUTHENTICATION_ERROR(CONNECTIVITY),
    UNKNOWN(CONNECTIVITY);

    private ErrorTypeDefinition<?> parentErrorType;

    @SuppressWarnings("rawtypes")
    Neo4jErrors(ErrorTypeDefinition parentErrorType) {
        this.parentErrorType = parentErrorType;
    }

    @Override
    public Optional<ErrorTypeDefinition<? extends Enum<?>>> getParent() {
        return ofNullable(parentErrorType);
    }
}
